### ISSUE TITLE
Grid takes no arguments

### ISSUE THREAD

**Issue by ro1713** [techwithtim/Sudoku-GUI-Solver#13]
The following error comes when the code mentioned above is executed.
Traceback (most recent call last):
  File "GUI.py", line 343, in <module>
    main()
  File "GUI.py", line 260, in main
    board = Grid(9, 9, 540, 540, win)
TypeError: Grid() takes no arguments

**Comment by satyabansahoo2000** [comment]
check line 20 it is taking 5 arguments. 
```def __init__(self, rows, cols, width, height, win):```
